# Generated by Django 6.0.5 on 2026-06-01 12:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Primary key (UUID) for the NGO', primary_key=True, serialize=False)),
                ('external_api_id', models.CharField(blank=True, help_text='External API ID if integrated', max_length=255, null=True)),
                ('name', models.CharField(help_text='Name of the NGO', max_length=255)),
                ('cnpj', models.CharField(help_text='CNPJ of the NGO (formatted or unformatted)', max_length=18, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the NGO', null=True)),
                ('focus_area', models.CharField(blank=True, help_text='Focus area of the NGO', max_length=255, null=True)),
                ('city', models.CharField(blank=True, help_text='City where the NGO is registered', max_length=255, null=True)),
                ('state', models.CharField(blank=True, help_text='State abbreviation (UF)', max_length=2, null=True)),
                ('current_score', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Current evaluation score (0-100)', max_digits=5, null=True)),
                ('years_operating', models.PositiveIntegerField(default=0, help_text='Years of operation based on CNPJ opening date')),
                ('address_valid', models.BooleanField(default=False, help_text='Whether the registered address matches public CEP data')),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('analysis', 'In Analysis'), ('pending', 'Pending'), ('inconsistent', 'Inconsistent')], default='pending', help_text='Current verification status of the NGO', max_length=20)),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='Timestamp of the last automated verification', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Flag indicating if the NGO CNPJ is active')),
                ('social_networks', models.JSONField(blank=True, default=list, help_text='List of social network entries, e.g. [{"platform": "instagram", "handle": "@ong"}]')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
            ],
            options={
                'verbose_name': 'NGO',
                'verbose_name_plural': 'NGOs',
                'db_table': 'ngo',
            },
        ),
    ]
