# Generated by Django 6.0.6 on 2026-06-07 03:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cause', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('match_multiplier', models.PositiveSmallIntegerField(default=1)),
                ('match_sponsor', models.CharField(blank=True, max_length=255, null=True)),
                ('eligibility_rules', models.JSONField(blank=True, default=list, help_text='List of eligibility rule strings')),
                ('distribution_rules', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ngos', models.ManyToManyField(blank=True, related_name='bundles', to='verification.ngo')),
            ],
            options={
                'db_table': 'bundle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cause', models.CharField(help_text="Cause slug, e.g. 'meio-ambiente'", max_length=50)),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('match_multiplier', models.PositiveSmallIntegerField(default=1, help_text='Matchfunding multiplier (1 = no match)')),
                ('match_sponsor', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ngo', models.ForeignKey(help_text='The NGO running this campaign', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='verification.ngo')),
            ],
            options={
                'db_table': 'campaign',
                'ordering': ['-created_at'],
            },
        ),
    ]
