# Generated by Django 6.0.6 on 2026-06-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_bundle_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='destination',
            field=models.TextField(blank=True, help_text='How the funds will be used', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(blank=True, help_text='Campaign expiration date', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='match_cap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum matchfunding amount limit', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='match_period',
            field=models.CharField(blank=True, help_text="E.g., 'Jun-Ago 2026'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='requirements',
            field=models.TextField(blank=True, help_text='Specific requirements for the campaign', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('em-revisao', 'Em Revisão'), ('aprovada', 'Aprovada'), ('publicada', 'Publicada'), ('recusada', 'Recusada'), ('encerrada', 'Encerrada'), ('arquivada', 'Arquivada')], default='rascunho', max_length=20),
        ),
        migrations.AddField(
            model_name='ngo',
            name='last_external_audit',
            field=models.DateField(blank=True, help_text='Date of the last external audit', null=True),
        ),
    ]
