# Generated by Django 6.0.5 on 2026-06-07 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_campaign_destination_campaign_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='pix_key',
            field=models.CharField(blank=True, help_text='Chave PIX da ONG', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ngo',
            name='user',
            field=models.OneToOneField(blank=True, help_text='User account associated with this NGO', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ngo_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
