# Generated by Django 6.0.6 on 2026-06-07 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='Telefone de contato do doador', max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, help_text='Data de nascimento do doador', null=True)),
                ('preferred_causes', models.JSONField(blank=True, default=list, help_text="Lista de causas de interesse, ex: ['meio-ambiente', 'educacao']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Usuário associado ao perfil de doador', on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Doador',
                'verbose_name_plural': 'Perfis de Doadores',
                'db_table': 'donor_profile',
            },
        ),
    ]
