# Generated by Django 6.0.6 on 2026-06-08 13:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('verification', '0004_ngo_pix_key_ngo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='verification.ngo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
