# Generated by Django 6.0.6 on 2026-06-08 17:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transparency', '0001_initial'),
        ('verification', '0004_ngo_pix_key_ngo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGODocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('document_url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='verification.ngo')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
