# Generated by Django 6.0.6 on 2026-06-08 19:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transparency', '0002_ngodocument'),
        ('verification', '0004_ngo_pix_key_ngo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGOReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('period', models.CharField(help_text="e.g. '30-days', '3-months', 'custom'", max_length=50)),
                ('include_finance', models.BooleanField(default=True)),
                ('include_donors', models.BooleanField(default=True)),
                ('include_campaigns', models.BooleanField(default=False)),
                ('include_cnpj', models.BooleanField(default=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='verification.ngo')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
